# GENERATED by `fwgitops scaffold-root`. Do not edit by hand.
#
# These mirror modules/security_folder/variables.tf ATTRIBUTE FOR
# ATTRIBUTE. Terraform discards an undeclared object attribute at the
# module boundary silently — no warning, exit 0 — so a root that drifts
# from the module does not fail, it quietly stops delivering part of
# every intent (ADR-0004, HOLE 3).
#
# Change the MODULE, then run `fwgitops scaffold-root --sync`.
# `--check` runs in CI; tests/test_tfroots.py verifies the result
# independently, because a generator marking its own homework is worth
# little.
#
# Values arrive from *.auto.tfvars.json, which Terraform auto-loads.
# Defaults are empty so `plan` works for a scope with nothing compiled
# into it yet — which is every scope on its first day.


variable "address_objects" {
  description = "Map of address object name -> definition (from the compiler)."
  type = map(object({
    name   = string
    type   = string # "ip-netmask" | "fqdn"
    value  = string
    folder = string
    tags   = list(string)
  }))
  default = {}
}

variable "folder" {
  description = "SCM folder these objects/rules live in. Also scopes the scm_tag objects."
  type        = string
  default     = "prod-edge"
}

variable "folder_interfaces" {
  description = <<-EOT
    Folder-scope `$`-interface VARIABLES, from catalog/interfaces.yaml via
    `fwgitops folder-interfaces`. SEPARATE from `interfaces` because both arrive
    as auto-loaded .tfvars and Terraform REPLACES a variable set twice rather
    than merging it — one variable name would let whichever file loads last
    erase the other, with no diagnostic.
  EOT
  type = map(object({
    name = string
    # Exactly one of folder/device is non-null (the provider enforces "exactly
    # one of device, folder, snippet"). A firewall is the last level of the SCM
    # hierarchy and inherits down it, but is addressed `device=`, never
    # `folder=`. A device-scope write to an inherited object creates a
    # per-device OVERRIDE — verified in spike/device-override-probe.
    folder = optional(string)
    device = optional(string)
    # FOLDER-SCOPE VARIABLES ONLY. On this tenant a folder-scope interface is a
    # `$`-prefixed VARIABLE whose default_value names the physical port every
    # firewall beneath the folder resolves it to. A zone can only bind an
    # interface object that exists at its scope -- binding a literal port name is
    # refused as an invalid reference -- so this attribute is what makes a
    # folder's zones bindable at all. Null at device scope, where the object IS
    # the physical port.
    default_value = optional(string)
    comment       = optional(string)
    layer3 = optional(object({
      ip          = optional(list(object({ name = string })))
      dhcp_client = optional(object({ enable = optional(bool) }))
      mtu         = optional(number)
      # Which admin services answer here. Attaching one to a DATA interface
      # exposes admin services on that network — absence is the safe default.
      interface_management_profile = optional(string)
    }))
  }))
  default = {}
}

variable "interfaces" {
  description = "Map of interface name -> configuration (InterfaceRequest, ADR-0001)."
  type = map(object({
    name = string
    # Exactly one of folder/device is non-null (the provider enforces "exactly
    # one of device, folder, snippet"). A firewall is the last level of the SCM
    # hierarchy and inherits down it, but is addressed `device=`, never
    # `folder=`. A device-scope write to an inherited object creates a
    # per-device OVERRIDE — verified in spike/device-override-probe.
    folder = optional(string)
    device = optional(string)
    # FOLDER-SCOPE VARIABLES ONLY. On this tenant a folder-scope interface is a
    # `$`-prefixed VARIABLE whose default_value names the physical port every
    # firewall beneath the folder resolves it to. A zone can only bind an
    # interface object that exists at its scope -- binding a literal port name is
    # refused as an invalid reference -- so this attribute is what makes a
    # folder's zones bindable at all. Null at device scope, where the object IS
    # the physical port.
    default_value = optional(string)
    comment       = optional(string)
    layer3 = optional(object({
      ip          = optional(list(object({ name = string })))
      dhcp_client = optional(object({ enable = optional(bool) }))
      mtu         = optional(number)
      # Which admin services answer here. Attaching one to a DATA interface
      # exposes admin services on that network — absence is the safe default.
      interface_management_profile = optional(string)
    }))
  }))
  default = {}
}

variable "routers" {
  description = "Map of logical router name -> definition (RouteRequest, ADR-0001)."
  type = map(object({
    name = string
    # Exactly one of folder/device is non-null (the provider enforces "exactly
    # one of device, folder, snippet"). A firewall is the last level of the SCM
    # hierarchy and inherits down it, but is addressed `device=`, never
    # `folder=`. A device-scope write to an inherited object creates a
    # per-device OVERRIDE — verified in spike/device-override-probe.
    folder = optional(string)
    device = optional(string)
    vrf = optional(list(object({
      name      = string
      interface = optional(list(string))
      routing_table = optional(object({
        ip = optional(object({
          static_route = optional(list(object({
            name        = string
            destination = optional(string)
            nexthop = optional(object({
              ip_address = optional(string)
            }))
            interface  = optional(string)
            metric     = optional(number)
            admin_dist = optional(number)
          })))
        }))
      }))
    })))
  }))
  default = {}
}

variable "security_rules" {
  description = "Map of rule key (stable for_each key) -> rule definition."
  type = map(object({
    name         = string
    folder       = string
    from_zones   = list(string)
    to_zones     = list(string)
    sources      = list(string)
    destinations = list(string)
    services     = list(string)
    action       = string # "allow" | "deny"
    log_end      = bool
    disabled     = optional(bool, false)
    tags         = list(string)
    # ── ADR-0003 rule components (optional; defaults = plain L4 allow) ──
    application       = optional(list(string), ["any"])
    profile_group     = optional(string) # null -> no security profile
    log_setting       = optional(string) # null -> local logs only
    rulebase          = optional(string, "pre")
    relative_position = optional(string, "bottom") # top|bottom|before|after
    target_rule       = optional(string)           # anchor for before/after
    # ── v1.0 rule completeness ──
    # Set explicitly, per the provider's own scm_security_rule example. Omitting
    # `category` / `source_user` is not "leave alone": the provider models
    # source_user as optional-NOT-computed, so absent config means REMOVE.
    description        = optional(string)
    log_start          = optional(bool, false)
    source_user        = optional(list(string), ["any"])
    category           = optional(list(string), ["any"])
    negate_source      = optional(bool, false)
    negate_destination = optional(bool, false)
  }))
  default = {}
}

variable "service_objects" {
  description = "Map of service object name -> definition."
  type = map(object({
    name     = string
    protocol = string # "tcp" | "udp"
    port     = string # "443" or "8000-8100"
    folder   = string
    tags     = list(string)
  }))
  default = {}
}

variable "zones" {
  description = "Map of zone name -> zone definition (ZoneRequest, ADR-0001)."
  type = map(object({
    name = string
    # Exactly one of folder/device is non-null (the provider enforces "exactly
    # one of device, folder, snippet"). A firewall is the last level of the SCM
    # hierarchy and inherits down it, but is addressed `device=`, never
    # `folder=`. A device-scope write to an inherited object creates a
    # per-device OVERRIDE — verified in spike/device-override-probe.
    folder = optional(string)
    device = optional(string)
    network = optional(object({
      layer2       = optional(list(string))
      layer3       = optional(list(string))
      external     = optional(list(string))
      tap          = optional(list(string))
      virtual_wire = optional(list(string))
      # ── security posture (ADR-0003 equivalent for zones) ──────────────
      # A zone with no protection profile has NO flood or reconnaissance
      # protection. The risk classifier flags that; it is not silently fine.
      zone_protection_profile         = optional(string)
      log_setting                     = optional(string)
      enable_packet_buffer_protection = optional(bool)
    }))
    # User-ID must be enabled PER ZONE or a rule matching on `source_user`
    # never matches — the rule model has supported source_user since v1.0.
    enable_user_identification   = optional(bool)
    enable_device_identification = optional(bool)
    dos_profile                  = optional(string)
    dos_log_setting              = optional(string)
    user_acl = optional(object({
      include_list = optional(list(string))
      exclude_list = optional(list(string))
    }))
    device_acl = optional(object({
      include_list = optional(list(string))
      exclude_list = optional(list(string))
    }))
  }))
  default = {}
}
