"""Re-attach Terraform state to SCM objects this pipeline already created.

WHY THIS EXISTS. State lives in an S3 bucket in the pilot's AWS account, and that
account is a time-limited subscription. On 2026-08-29 it expired: the bucket
went with it, every nightly run failed on OIDC for 17 days, and the new bucket
started EMPTY. An apply against empty state tries to CREATE every rule that
already exists in SCM.

The recovery on 2026-09-14 was a hand-written script in a scratch directory:
list what each root declares, read each object's live id, write `import` blocks,
and refuse to go on unless the plan adds and destroys nothing. This is that
script, kept.

STATE RECOVERY, NOT ADOPTION. ADR-0011 forbids importing hand-made config to
make it managed. Everything imported here is DECLARED in Git — it is read from
the compiled tfvars, never from SCM — and SCM supplies only the id. An object
SCM holds that Git does not declare is never imported; it is not even looked at.

IDS. Both forms were read from live state rather than inferred from the provider
docs' placeholders:

    folder  prod-edge:::<uuid>          (scm_security_rule.tfid, 2026-09-14)
    device  ::007955000919340:<uuid>    (scm_ethernet_interface.tfid, 2026-09-15)

PURE where it can be. `import_blocks` takes declared objects and live rows and
returns text, so the part that decides WHAT to import is tested without SCM.
"""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any, Dict, Iterable, List, Mapping, Optional, Tuple

#: tfvars variable -> (resource type, SCM list path, extra query params).
#: `folder_interfaces` and `interfaces` share one resource: the module merges
#: them into a single `scm_ethernet_interface.this` for_each.
RESOURCES: Dict[str, Tuple[str, str, Dict[str, str]]] = {
    "security_rules": ("scm_security_rule", "/config/security/v1/security-rules",
                       {"position": "pre"}),
    "zones": ("scm_zone", "/config/network/v1/zones", {}),
    "routers": ("scm_logical_router", "/config/network/v1/logical-routers", {}),
    "folder_interfaces": ("scm_ethernet_interface",
                          "/config/network/v1/ethernet-interfaces", {}),
    "interfaces": ("scm_ethernet_interface",
                   "/config/network/v1/ethernet-interfaces", {}),
}

MODULE = "module.security_folder"
FILENAME = "imports_recovery.tf"


@dataclass(frozen=True)
class Scope:
    """A Terraform root's SCM address: a folder name, or a device serial."""

    kind: str   # "folder" | "device"
    value: str

    @classmethod
    def of_root(cls, root: Path) -> "Scope":
        name = root.name
        if name.startswith("device-"):
            return cls("device", name[len("device-"):])
        return cls("folder", name)

    @property
    def params(self) -> Dict[str, str]:
        return {self.kind: self.value}

    def import_id(self, uuid: str) -> str:
        return (f"{self.value}:::{uuid}" if self.kind == "folder"
                else f"::{self.value}:{uuid}")

    def owns(self, row: Mapping[str, Any]) -> bool:
        """Defined HERE, not inherited. A list call returns ancestors' objects too,
        and importing an inherited one would put a parent folder's object in a
        child's state — a later destroy would delete it for every sibling."""
        return row.get(self.kind) == self.value


@dataclass
class Recovery:
    scope: Scope
    blocks: List[str] = field(default_factory=list)
    #: declared in Git but absent from SCM — cannot be imported, WILL be created
    missing: List[str] = field(default_factory=list)

    def render(self) -> str:
        head = (f"# GENERATED by `fwgitops recover-state` — state recovery for "
                f"{self.scope.kind} {self.scope.value}.\n"
                f"# Import blocks for objects Git declares and SCM already holds.\n"
                f"# Delete this file once the apply has landed.\n")
        return head + "\n".join(self.blocks)


def declared_objects(root: Path) -> Dict[str, Dict[str, Any]]:
    """tfvars variable -> {for_each key: spec}, from every compiled file in a root."""
    out: Dict[str, Dict[str, Any]] = {}
    for f in sorted(root.glob("*.auto.tfvars.json")):
        for var, value in json.loads(f.read_text()).items():
            if var in RESOURCES and isinstance(value, dict):
                out.setdefault(var, {}).update(value)
    return out


def import_blocks(scope: Scope, declared: Mapping[str, Mapping[str, Any]],
                  live: Mapping[str, Iterable[Mapping[str, Any]]]) -> Recovery:
    """Pair every DECLARED object with the live row of the same name at this scope."""
    rec = Recovery(scope)
    for var in sorted(declared):
        rtype = RESOURCES[var][0]
        by_name = {str(r.get("name")): r for r in live.get(var, ())
                   if isinstance(r, Mapping) and scope.owns(r) and r.get("id")}
        for key in sorted(declared[var]):
            spec = declared[var][key]
            name = str(spec.get("name", key)) if isinstance(spec, Mapping) else str(key)
            row = by_name.get(name)
            if row is None:
                rec.missing.append(f'{rtype}["{key}"]')
                continue
            rec.blocks.append(
                f'import {{\n  to = {MODULE}.{rtype}.this["{key}"]\n'
                f'  id = "{scope.import_id(str(row["id"]))}"\n}}\n')
    return rec


def read_live(session: Any, scope: Scope, variables: Iterable[str]) -> Dict[str, List[dict]]:
    """One SCM list call per resource path this root declares."""
    cache: Dict[Tuple[str, str], List[dict]] = {}
    out: Dict[str, List[dict]] = {}
    for var in variables:
        _, path, extra = RESOURCES[var]
        k = (path, json.dumps(extra, sort_keys=True))
        if k not in cache:
            payload = session.request("GET", path,
                                      params={**scope.params, "limit": 500, **extra})
            cache[k] = list((payload or {}).get("data") or [])
        out[var] = cache[k]
    return out


def recover_root(session: Any, root: Path) -> Recovery:
    scope = Scope.of_root(root)
    declared = declared_objects(root)
    return import_blocks(scope, declared, read_live(session, scope, declared))


def plan_is_safe(plan_line: Optional[str]) -> bool:
    """`Plan: N to import, A to add, C to change, D to destroy.` with A == D == 0.

    In-place CHANGES are allowed: an import id cannot carry `position = "pre"`,
    so every imported rule shows one. An ADD means Terraform would create an
    object SCM already has; a DESTROY means it would delete one. Either is the
    failure this exists to prevent. `No changes.` is safe too (nothing to import).
    """
    import re

    if plan_line is None:
        return False
    if plan_line.startswith("No changes"):
        return True
    m = re.search(r"(\d+) to add, (\d+) to change, (\d+) to destroy", plan_line)
    return bool(m) and m.group(1) == "0" and m.group(3) == "0"
